# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
