# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170919_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
